### PR TITLE
Add a benchmark for disabled log levels

### PR DESCRIPTION
**Pull request by akshayjshah**
Realized that we weren't benchmarking the overhead of disabled logging. It's not free, but it's pretty close.

```
BenchmarkZapDisabledLevels-4    200000000                6.07 ns/op            0 B/op          0 allocs/op
```

### CODE REVIEW

**Comment by blampe** [comment]
🚢

**Comment by prashantv** [comment]
Can you also add benchmarks with some fields? (I think unfortunately we'll still do allocs even with a level disabled)

**Comment by akshayjshah** [comment]
Done. Results are as expected - we allocate for the slice to hold the variadic args and when casting concrete types to interfaces.

```
BenchmarkZapDisabledLevelsWithoutFields-4           200000000                7.78 ns/op            0 B/op          0 allocs/op
BenchmarkZapDisabledLevelsAccumulatedContext-4  200000000                6.48 ns/op            0 B/op          0 allocs/op
BenchmarkZapDisabledLevelsAddingFields-4         3000000               353 ns/op             704 B/op          2 allocs/op
BenchmarkZapWithoutFields-4                     10000000               220 ns/op               0 B/op          0 allocs/op
BenchmarkZapWithAccumulatedContext-4             5000000               233 ns/op               0 B/op          0 allocs/op
BenchmarkZapAddingFields-4                       1000000              1129 ns/op             705 B/op          2 allocs/op
```

**Comment by prashantv** [comment]
Thanks, yep that's what I expected. We'll probably want to do a "is level enabled" check before logging in the critical path (especially for debugging logging) similar to TChannel-Go.

lgtm

**Pull request merged**
